# Generated by Django 2.2 on 2019-05-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='specilization',
            field=models.CharField(choices=[('math', 'Math'), ('physics', 'Physics'), ('arts', 'Arts'), ('cs', 'Computer Science')], default='math', max_length=10),
        ),
    ]
