# Generated by Django 2.2 on 2019-05-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190526_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise_quest_answer',
            name='code_snippet',
            field=models.TextField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
