# Generated by Django 2.2 on 2019-05-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exercise_quest_answer_code_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_quest_answer',
            name='code_snippet',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
